---
- name: install mysql, php, php extensions, and spawn-fcgi
  apt: name={{item}} state=present
  with_items:
  - python-mysqldb # for ansible
  - default-mysql-server
  - php7.0-cgi
  - php7.0-mysqlnd
  - php7.0-curl
  - php7.0-simplexml
  - php7.0-mcrypt
  - php7.0-gd
  - php7.0-dom
  - php7.0-soap
  - php7.0-zip
  - php7.0-fileinfo
  - php7.0-intl
  - spawn-fcgi
  notify:
  - restart prestashop
- name: create user prestashop
  user: name=prestashop shell=/usr/sbin/nologin
- name: create mysql database prestashop
  mysql_db: name=prestashop state=present
- name: create mysql database user prestashop
  mysql_user: name=prestashop state=present priv=prestashop.*:ALL
- name: create webroot for prestashop
  file: dest={{webroot}} state=directory owner=prestashop
- name: install prestashop {{install_version}}
  unarchive: dest={{webroot}} creates={{webroot}}/index.php remote_src=yes
    src=https://download.prestashop.com/download/releases/prestashop_{{install_version}}.zip
  become: true
  become_user: prestashop
  register: app_install
  notify:
  - prestashop post-installation message
- name: check if prestashop needs first-run adjustment
  stat: path={{webroot}}/install
  register: install_dir
  when: app_install.skipped
- name: rename the admin directory
  command: mv {{webroot}}/admin {{webroot}}/xadmin
  when: install_dir.stat.exists
- name: remove installation artifacts
  file: dest={{item}} state=absent
  with_items:
  - "{{webroot}}/install/"
  - "{{webroot}}/Install_PrestaShop.html"
  - "{{webroot}}/INSTALL.txt"
  when: install_dir.stat.exists
- name: enable always-on https
  command: mysql prestashop
      -u prestashop
      -e "UPDATE configuration SET value = 1 WHERE name = 'PS_SSL_ENABLED';"
      -e "INSERT INTO configuration (name, value) VALUES ('PS_SSL_ENABLED_EVERYWHERE', 1)
                 ON DUPLICATE KEY UPDATE value = 1;"
  become: true
  become_user: prestashop
  when: want_tls
- name: add prestashop init script
  copy: dest=/etc/init.d/prestashop src=rc.sh mode=0755
  notify:
  - restart prestashop
- name: enable prestashop service
  service: name=prestashop state=started enabled=yes
