---
- import_tasks: app.yml
  tags:
  - prestashop
  - prestashop:app
  # force eager expansion of variables so that nginx-site below uses exactly what we want
- name: determine path to nginx site template
  set_fact:
    nginx_conf={{role_path}}/templates/nginx.conf
    webroot={{webroot}} # or nginx-site's default will override ours
  tags:
  - prestashop
  - prestashop:nginx
- include_role: name=nginx-site
  tags:
  - prestashop
  - prestashop:nginx
- name: configure prestashop cron adapter
  cron:
    name: prestashop
    minute: 0
    job: /bin/bash -c 'set -o pipefail; curl -sSf "https://{{domain}}/xadmin/index.php?controller=AdminCronJobs&token={{prestashop.cron_token}}" | grep -v cronjobs_prestashop'
  when: prestashop.cron_token is defined
  tags:
  - prestashop
  - prestashop:cron
