---
- name: synchronizing files
  command: |
    rsync -azI --rsh="ssh -o StrictHostKeyChecking=no"
      {{hostvars[remote_host].ansible_user}}@{{remote_host}}:{{webroot}}/ {{webroot}}/
- name: dumping database
  command: mysqldump -u prestashop -r /tmp/prestashop_sync.sql prestashop
  become: true
  become_user: prestashop
  delegate_to: '{{remote_host}}'
- name: downloading database
  fetch: dest=/tmp/prestashop_sync.sql src=/tmp/prestashop_sync.sql flat=true
  delegate_to: '{{remote_host}}'
- name: restoring database
  command: sh -c 'mysql -u prestashop prestashop < /tmp/prestashop_sync.sql'
  become: true
  become_user: prestashop
- name: removing database dumps
  file: dest=/tmp/prestashop_sync.sql state=absent
  delegate_to: '{{item}}'
  with_items:
  - '{{inventory_hostname}}'
  - '{{remote_host}}'
- name: update configuration
  command: mysql prestashop
      -u prestashop
      -e "UPDATE configuration SET value = 0
                 WHERE name IN ('PS_SSL_ENABLED', 'PS_SSL_ENABLED_EVERYWHERE');"
      -e "UPDATE shop_url SET domain = 'localhost', domain_ssl = 'localhost';"
  become: true
  become_user: prestashop
