---
- name: install nginx, and certbot if needed
  apt: name={{item.name}} state=present
  with_items:
  - { name: nginx-full }
  - { name: certbot, enabled: "{{want_tls}}" }
  when: item.enabled | default(true) | bool
  register: install_nginx
- name: remove default nginx site
  file: name=/etc/nginx/sites-enabled/default state=absent
- name: copy nginx tls_params
  copy: dest=/etc/nginx/tls_params src=tls_params.conf
  notify:
  - reload nginx
  when: want_tls
- name: configure certbot to renew regularly
  cron: name="certbot" minute="0" hour="{{ 23 | random(seed=inventory_hostname) }}"
    job="certbot renew --quiet --renew-hook '/etc/init.d/nginx reload'"
  when: want_tls
- name: cache the fact that nginx is installed
  set_fact: nginx_is_installed=true cacheable=yes
  when: not install_nginx.changed
