---
- hosts: uruz.whitequark.org
  remote_user: root
  tasks:
  - include: tasks/apt.yml
    tags: apt
  - include: tasks/nsd.yml
    tags: nsd
  - include: tasks/user.yml
    tags: user
  - include: tasks/nginx.yml
    tags: nginx
  - include: tasks/nginx-site.yml name=uruz.whitequark.org
    tags: nginx
  handlers:
  - include: handlers/nsd.yml
  - include: handlers/nginx.yml
