---
- hosts: uruz.whitequark.org
  vars:
    live: yes
    want_tls: yes
  vars_files:
  - vars/private.yml
  pre_tasks:
  - include: tasks/apt.yml
    tags: apt
  - include: tasks/system.yml
    tags: system
  - include: tasks/personal.yml
    tags: personal
  - include: tasks/nsd.yml
    tags: nsd
  - include: tasks/nsd-zone.yml name=whitequark.org
    tags: nsd, nsd:whitequark.org
  - include: tasks/nsd-zone.yml name=llvm.moe
    tags: nsd, nsd:llvm.moe
  - include: tasks/mail.yml domain=mail.whitequark.org
    tags: mail
  - import_role: name=nginx
  - import_role: name=nginx-site
    vars:
      domain: uruz.whitequark.org
    tags: uruz.whitequark.org:nginx-site
  - import_role: name=nginx-site
    vars:
      domain: www.whitequark.org
    tags: www.whitequark.org:nginx-site
  - include: tasks/roundcube.yml domain=mail.whitequark.org
    tags: mail.whitequark.org
  - import_role: name=prestashop
    vars:
      domain: shop.whitequark.org
  - include: tasks/sites/doc.whitequark.org.yml
    tags: doc.whitequark.org
  - include: tasks/sites/files.whitequark.org.yml
    tags: files.whitequark.org
  - include: tasks/sites/lab.whitequark.org.yml
    tags: lab.whitequark.org
  - include: tasks/sites/groupxiv.whitequark.org.yml
    tags: groupxiv.whitequark.org
  - include: tasks/sites/irclog.whitequark.org.yml
    tags: irclog.whitequark.org
  - include: tasks/nginx-site.yml name=mail.whitequark.org
    tags: mail.whitequark.org, mail.whitequark.org:nginx
  - include: tasks/sites/whitequark.org.yml
    tags: whitequark.org
  - import_role: name=nginx-site
    vars:
      domain: whitequark.com
    tags: whitequark.com:nginx-site
  - include: tasks/sites/llvm.moe.yml
    tags: llvm.moe
  - include: tasks/mumble.yml
    tags: mumble
  - include: tasks/tarsnap.yml
    tags: tarsnap
  - include: tasks/backup.yml
    tags: backup
  handlers:
  - include: handlers/sysctl.yml
  - include: handlers/syslog.yml
  - include: handlers/nsd.yml
  - include: handlers/mail.yml
  - include: handlers/mysql.yml
  - include: handlers/roundcube.yml
  - include: handlers/sites/irclog.whitequark.org.yml
  - include: handlers/mumble.yml
