---
- hosts: uruz.whitequark.org
  remote_user: root
  vars:
    live: False
  tasks:
  - include: tasks/apt.yml
    tags: apt
  - include: tasks/nsd.yml
    tags: nsd
  - include: tasks/user.yml
    tags: user
  - include: tasks/nginx.yml
    tags: nginx
  - include: tasks/nginx-site.yml name=uruz.whitequark.org
    tags: nginx
  - include: tasks/sites/www.whitequark.org.yml
    tags: www.whitequark.org
  - include: tasks/sites/doc.whitequark.org.yml
    tags: doc.whitequark.org
  - include: tasks/sites/lab.whitequark.org.yml
    tags: lab.whitequark.org
  - include: tasks/sites/groupxiv.whitequark.org.yml
    tags: groupxiv.whitequark.org
  - include: tasks/sites/irclog.whitequark.org.yml
    tags: irclog.whitequark.org
  - include: tasks/sites/llvm.moe.yml
    tags: llvm.moe
  handlers:
  - include: handlers/nsd.yml
  - include: handlers/nginx.yml
  - include: handlers/sites/irclog.whitequark.org.yml
