---
- hosts: uruz.whitequark.org
  remote_user: root
  vars:
    live: True
  vars_files:
    - vars/passwords.yml
  tasks:
  - include: tasks/apt.yml
    tags: apt
  - include: tasks/system.yml
    tags: system
  - include: tasks/personal.yml
    tags: personal
  - include: tasks/mail.yml
    tags: mail
  - include: tasks/nsd.yml
    tags: nsd
  - include: tasks/nsd-zone.yml name=whitequark.org
    tags: nsd
  - include: tasks/nsd-zone.yml name=llvm.moe
    tags: nsd
  - include: tasks/nginx.yml
    tags: nginx
  - include: tasks/nginx-site.yml name=uruz.whitequark.org
    tags: nginx
  - include: tasks/sites/www.whitequark.org.yml
    tags: www.whitequark.org
  - include: tasks/sites/doc.whitequark.org.yml
    tags: doc.whitequark.org
  - include: tasks/sites/files.whitequark.org.yml
    tags: files.whitequark.org
  - include: tasks/sites/lab.whitequark.org.yml
    tags: lab.whitequark.org
  - include: tasks/sites/groupxiv.whitequark.org.yml
    tags: groupxiv.whitequark.org
  - include: tasks/sites/irclog.whitequark.org.yml
    tags: irclog.whitequark.org
  - include: tasks/sites/mail.whitequark.org.yml
    tags: mail.whitequark.org
  - include: tasks/sites/whitequark.org.yml
    tags: whitequark.org
  - include: tasks/sites/llvm.moe.yml
    tags: llvm.moe
  - include: tasks/tarsnap.yml version=1.0.37
    tags: tarsnap
  - include: tasks/backup.yml
    tags: backup
  handlers:
  - include: handlers/syslog.yml
  - include: handlers/nsd.yml
  - include: handlers/mail.yml
  - include: handlers/nginx.yml
  - include: handlers/sites/irclog.whitequark.org.yml
  - include: handlers/sites/mail.whitequark.org.yml
