---
- hosts: uruz.whitequark.org
  remote_user: root
  tasks:
  - include: tasks/apt.yml
    tags: apt
  - include: tasks/nsd.yml
    tags: nsd
  - include: tasks/user.yml
    tags: user
  handlers:
  - include: handlers/nsd.yml
