---
database: postgres:///irclogs
redis: redis://localhost:6379

server: irc.freenode.net
username: irclogger-test
realname: whitequark's logger bot
nickname: logger_test
channels:
  - "#irclogger-test"
domain: irclog.whitequark.org
