---
database: postgres:///irclogs
redis: redis://localhost:6379

server: chat.freenode.net
username: whitelogger
realname: whitequark's logger bot
nickname: _whitelogger
password: {{irclogger_password}}
channels:
  - "#ruby-core"
  - "#ruby"
  - "#qi-hardware"
  - "#homecmos"
  - "#teamhacksung"
  - "#teamhacksung-support"
  - "#arm-netbook"
  - "#cinch"
  - "#rubygems"
  - "#rubygems-trust"
  - "#linux-sunxi"
  - "#elliottcable"
  - "#imx6-dev"
  - "#nanoc"
  - "#cubieboard"
  - "#Paws.Nucleus"
  - "#rom-rb"
  - "#datamapper"
  - "#linux-rockchip"
  - "#opal"
  - "#mutant"
  - "#radxa"
  - "#bundler"
  - "#rubygems-aws"
  - "#m-labs"
  - "#microrb"
  - "#ocaml"
  - "#mirage"
  - "#linux-exynos"
  - "#arm-graphics"
  - "#rubinius"
  - "#jruby"
  - "#libreoffice-ru"
  - "#coiniumserv"
  - "#coiniumserv-dev"
  - "#neo900"
  - "#crystal-lang"
  - "#huawei-g300"
  - "#maglev-ruby"
  - "#xiki"
  - "#stellar"
  - "#stellar-dev"
  - "#bitcoin-wizards"
  - "#sandstorm"
  - "#ipfs"
  - "#tinyqma"
  - "#ruby-rdf"
  - "#nextbsd"
  - "#systemtap"
  - "#ponylang"
  - "#gridcoin"
  - "#gridcoin-dev"
  - "#soletta"
  - "#reasonml"
hidden_channels:
  - "##fix_your_connection"
  - "#AUTOMATIOTT"
  - "#cuckoosandbox"
  - "#panda-re"
  - "#volatility"
  - "#kvm"
  - "#bedrock"
  - "#xen"
  - "#progressbar"
  - "#v01d"
  - "#base48"
  - "#brmlab"
  - "#nupic"
domain: irclog.whitequark.org
