- name: install mysql
  apt: name={{item}} state=present
  with_items:
    - default-mysql-server
    - python-mysqldb
- name: enable mysql auth_socket plugin
  copy: dest=/etc/mysql/conf.d/auth_socket.cnf src=templates/etc/mysql/conf.d/auth_socket.cnf
  notify:
    - restart mysql
  register: auth_socket
- name: restart mysql
  service: name=mysql state=restarted
  when: auth_socket.changed
- name: secure the mysql root user
  command: mysql -u root \
    -e "DROP USER 'root'@'localhost', 'root'@'::1', 'root'@'127.0.0.1';
        DROP USER 'root'@'{{inventory_hostname}}';
        GRANT ALL ON *.* TO 'root'@'localhost' IDENTIFIED WITH auth_socket;"
  when: auth_socket.changed
