- name: install nsd
  apt: name=nsd state=present
- name: configure nsd
  template: dest=/etc/nsd/nsd.conf src=templates/etc/nsd/nsd.conf
  notify:
    - reload nsd
- name: create /etc/nsd/zones
  file: path=/etc/nsd/zones state=directory
