# heads-up#1: this needs, after installation, the following executed under mysql:
# UPDATE configuration SET value = 1 WHERE name = 'PS_SSL_ENABLED';
# INSERT INTO configuration (name, value) VALUES ('PS_SSL_ENABLED_EVERYWHERE', 1);
# heads-up#2: this needs, after installation, the folder /admin renamed to /xadmin.
- name: install php and extensions for prestashop
  apt: name={{item}} state=present
  with_items:
    - php7.0
    - php7.0-mysqlnd
    - php7.0-curl
    - php7.0-simplexml
    - php7.0-mcrypt
    - php7.0-gd
    #- php7.0-openssl
    - php7.0-dom
    - php7.0-soap
    - php7.0-zip
    - php7.0-fileinfo
- name: create user prestashop
  user: name=prestashop shell=/usr/sbin/nologin
- name: create mysql database prestashop
  mysql_db: name=prestashop state=present
- name: create mysql database user prestashop
  mysql_user: name=prestashop state=present priv='prestashop.*:ALL'
- name: create webroot for {{domain}}
  file: dest=/var/www/{{domain}} state=directory owner=prestashop
- name: check if prestashop is installed
  stat: path=/var/www/{{domain}}/index.php
  register: prestashop_index
- name: install prestashop {{version}}
  unarchive: dest=/var/www/{{domain}} remote_src=yes
    src=https://download.prestashop.com/download/releases/prestashop_{{version}}.zip
  become: true
  become_user: prestashop
  when: prestashop_index.stat.exists == False
- name: install spawn-fcgi
  apt: name=spawn-fcgi state=present
- name: add prestashop init script
  copy: dest=/etc/init.d/prestashop src=templates/etc/init.d/prestashop mode=0755
  notify:
    - restart prestashop
- name: enable prestashop service
  service: name=prestashop state=started enabled=yes
- name: configure prestashop cron adapter
  cron:
    name: prestashop
    minute: 0
    job: /bin/bash -O pipefail -c 'curl -sSf "https://shop.whitequark.org/xadmin/index.php?controller=AdminCronJobs&token={{prestashop_cron_token}}" | grep -v cronjobs_prestashop'
