- name: install postgresql, dbconfig, and git
  apt: name={{item}} state=present
  with_items:
    - postgresql
    - dbconfig-pgsql
    - git
- name: create user roundcube
  user: name=roundcube shell=/usr/sbin/nologin
- name: configure postgresql roundcube database
  copy: dest=/etc/dbconfig-common/roundcube.conf src=templates/etc/dbconfig-common/roundcube.conf
- name: install roundcube
  apt: name={{item}} state=present
  with_items:
    - roundcube
    - roundcube-pgsql
    - roundcube-plugins
    # needs $ ln -s keyboard-shortcuts /var/lib/roundcube/keyboard_shortcuts, sigh
    - roundcube-plugins-extra
    - spawn-fcgi
    - php-pspell
  register: roundcube_apt
- name: remove useless roundcube packages
  apt: name={{item}} state=absent
  with_items:
    - apache2-bin
    - roundcube-mysql
- name: add roundcube init script
  copy: dest=/etc/init.d/roundcube src=templates/etc/init.d/roundcube mode=0755
  notify:
    - restart roundcube
- name: configure roundcube
  template: dest=/etc/roundcube/config.inc.php src=templates/etc/roundcube/config.inc.php
    group=roundcube mode=0644
- name: check for roundcube cookie
  stat: path=/etc/roundcube/cookie.inc.php
  register: roundcube_cookie
- name: configure roundcube cookie
  template: dest=/etc/roundcube/cookie.inc.php src=templates/etc/roundcube/cookie.inc.php
    group=roundcube mode=0644
  when: roundcube_cookie.stat.exists == False
- name: fix permissions on roundcube log and temp
  file: name={{item}} owner=roundcube group=roundcube state=directory recurse=yes
  with_items:
    - /var/lib/roundcube/temp
    - /var/log/roundcube
- name: enable roundcube service
  service: name=roundcube state=started enabled=yes
