- name: add tarsnap binary packaging key
  apt_key: url=https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc state=present
- name: add tarsnap deb repository
  apt_repository: repo='deb http://pkg.tarsnap.com/deb/stretch ./' state=present
  register: add_apt_repo
- name: update APT cache
  apt: update_cache=yes
  when: add_apt_repo.changed
- name: install tarsnap
  apt: name=tarsnap state=present
