- name: create user whitequark
  user: name=whitequark shell=/bin/bash
- name: add SSH authorized key for user whitequark
  authorized_key: user=whitequark key={{ lookup('file', '/home/whitequark/.ssh/id_rsa.pub') }}
- name: install personal packages
  apt: name={{item}} state=present
  with_items:
    - mc
    - pv
    - htop
    - mosh
    - tmux
    - irssi
    - strace
